In [1]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
        SELECT f.name,
        SUM(CASE WHEN b.memid <> 0 THEN (f.membercost * b.slots)
            ELSE (f.guestcost * b.slots) END)-f.monthlymaintenance AS revenue
        FROM Bookings AS b
        LEFT JOIN Facilities AS f ON f.facid = b.facid 
        GROUP BY f.name
        HAVING revenue < 1000
        ORDER BY revenue DESC
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Pool Table', 255)
('Snooker Table', 225)
('Table Tennis', 170)

In [6]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
        SELECT (m2.surname||', '||m2.firstname) AS ReferredBy,
        (m1.surname||', '||m1.firstname) AS Name
        FROM Members AS m1
        LEFT JOIN Members AS m2 ON m1.recommendedby = m2.memid
        WHERE m1.memid <> 0 AND m2.memid <> 0
        ORDER BY m1.surname, m1.firstname
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Stibbons, Ponder', 'Bader, Florence')
('Stibbons, Ponder', 'Baker, Anne')
('Farrell, Jemima', 'Baker, Timothy')
('Rownam, Tim', 'Boothe, Tim')
('Smith, Darren', 'Butters, Gerald')
('Baker, Timothy', 'Coplin, Joan')
('Smith, Tracy', 'Crumpet, Erica')
('Joplette, Janice', 'Dare, Nancy')
('Butters, Gerald', 'Genting, Matthew')
('Purview, Millicent', 'Hunt, John')
('Joplette, Janice', 'Jones, David')
('Jones, David', 'Jones, Douglas')
('Smith, Darren', 'Joplette, Janice')
('Smith, Darren', 'Mackenzie, Anna')
('Smith, Darren', 'Owen, Charles')
('Farrell, Jemima', 'Pinker, David')
('Smith, Tracy', 'Purview, Millicent')
('Genting, Matthew', 'Rumney, Henrietta')
('Bader, Florence', 'Sarwin, Ramnaresh')
('Smith, Darren', 'Smith, Jack')
('Tracy, Burton', 'Stibbons, Ponder')
('Smith, Tracy', 'Worthington-Smyth, Henry')

In [2]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
        SELECT f.name,
        SUM(b.slots) AS facility_usage
        FROM Bookings AS b
        LEFT JOIN Facilities AS f ON b.facid = f.facid
        WHERE b.memid <> 0
        GROUP BY f.name

        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Badminton Court', 1086)
('Massage Room 1', 884)
('Massage Room 2', 54)
('Pool Table', 856)
('Snooker Table', 860)
('Squash Court', 418)
('Table Tennis', 794)
('Tennis Court 1', 957)
('Tennis Court 2', 882)

In [3]:
import sqlite3
from sqlite3 import Error

 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn

 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
        SELECT f.name,
        SUBSTR(b.starttime, 6, 2) AS month,
        SUM(b.slots) AS facility_usage
        FROM Bookings AS b
        LEFT JOIN Facilities AS f ON b.facid = f.facid
        WHERE b.memid <> 0
        GROUP BY f.name, month
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "sqlite_db_pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Badminton Court', '07', 165)
('Badminton Court', '08', 414)
('Badminton Court', '09', 507)
('Massage Room 1', '07', 166)
('Massage Room 1', '08', 316)
('Massage Room 1', '09', 402)
('Massage Room 2', '07', 8)
('Massage Room 2', '08', 18)
('Massage Room 2', '09', 28)
('Pool Table', '07', 110)
('Pool Table', '08', 303)
('Pool Table', '09', 443)
('Snooker Table', '07', 140)
('Snooker Table', '08', 316)
('Snooker Table', '09', 404)
('Squash Court', '07', 50)
('Squash Court', '08', 184)
('Squash Court', '09', 184)
('Table Tennis', '07', 98)
('Table Tennis', '08', 296)
('Table Tennis', '09', 400)
('Tennis Court 1', '07', 201)
('Tennis Court 1', '08', 339)
('Tennis Court 1', '09', 417)
('Tennis Court 2', '07', 123)
('Tennis Court 2', '08', 345)
('Tennis Court 2', '09', 414)